alienartifacts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static # new
from django.conf import settings # new

app_name = 'alienartifacts'

urlpatterns = [
    #Example urls
    #Task-specific urls
    path("", views.index, name="index"),
    path("welcome", views.welcome, name="welcome"),
    path("attentionfailure", views.attentionfailure, name="attentionfailure"),
    path("consentform", views.consentform, name="consentform"),
    path("questionnaires", views.questionnaires, name="questionnaires"),
    path("instructions", views.instructions, name="instructions"),
    path("onepageexamplegentask", views.onePageExampleGenTask, name="onepageexamplegentask"),
    path('onepageexamplegenupdate', views.onePageExampleGenUpdate, name='onepageexamplegenupdate'),
    path("onepagecontextgentask", views.onePageContextGenTask, name="onepagecontextgentask"),
    path('onepagecontextgenupdate', views.onePageContextGenUpdate, name='onepagecontextgenupdate'),
    path("onepagediagnostic", views.onePageDiagnostic, name="onepagediagnostic"),
    path('onepagediagnosticupdate', views.onePageDiagnosticUpdate, name='onepagediagnosticupdate'),
    path("tutorial", views.tutorial, name="tutorial"),
    path("feedback", views.feedback, name="feedback"),
    path("goodbye", views.goodbye, name="goodbye"),
    path('token', views.token, name='token'),
    path('fishy', views.fishy, name='fishy'),
    path('alreadycompleted', views.alreadyCompleted, name='alreadycompleted')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

azuresite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings # new
from django.urls import path, include # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('', include('alienartifacts.urls')),
    path('admin/', admin.site.urls),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alienartifacts/models.py
import datetime

from django.db import models
from django.utils import timezone


class Stimulus(models.Model):
    #Contains stimuli used in the task, organized according to attributes
    color = models.CharField(max_length=64)
    shape = models.CharField(max_length=64)
    texture = models.CharField(max_length=64)
    size = models.CharField(max_length=64,default='')
    reward_probabilities = models.JSONField(default=dict)
    image = models.ImageField(upload_to='images/')


class TutorialStimulus(models.Model):
    spaceship = models.CharField(max_length=64)
    setting = models.CharField(max_length=64)
    reward_probabilities = models.JSONField(default=dict)
    image = models.ImageField(upload_to='images/')


class RewardStimulus(models.Model):
    outcome = models.CharField(max_length=64)
    type = models.CharField(max_length=64)
    image = models.ImageField(upload_to='images/')


class Subject(models.Model):
    #Contains user index, external identification number, where they came from
    external_ID = models.CharField(max_length=64)
    external_source = models.CharField(max_length=64)
    age = models.CharField(max_length=20)
    gender = models.CharField(max_length=20)
    education = models.CharField(max_length=20)
    is_bot = models.BooleanField(default=False)
    psych_history = models.JSONField(default=list,blank=True,null=True)


class Session(models.Model):
    #Summary details, such as length, number of stimuli seen, average performance, date, etc.
    n_trials = models.IntegerField(default=0)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    session_completed = models.BooleanField(default=False)
    tutorial_completed = models.BooleanField(default=False)
    conditioning_completed = models.BooleanField(default=False)
    total_reward = models.IntegerField(default=0)
    total_payment = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    payment_issued = models.BooleanField(default=False)
    final_performance = models.DecimalField(max_digits=6, decimal_places=5, null=True)
    payment_token = models.CharField(max_length=40)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="sessions")
    strategy = models.CharField(max_length=1000, default="")
    strategy_radio = models.CharField(max_length=30, default="")
    perceived_difficulty = models.CharField(max_length=10, default="")
    conditioning_attributes = models.JSONField(default=list)
    generalization_attributes = models.JSONField(default=list)
    set_1_attribute = models.JSONField(default=list)
    set_2_attribute = models.JSONField(default=list)
    task = models.CharField(max_length=100, default="")
    key_conversion = models.JSONField(default=dict)
    substances = models.JSONField(default=list,blank=True,null=True)
    passed_attention_check = models.BooleanField(default=True)


class Trial(models.Model):
    #All data pertinent for an individual trial
    stimulus = models.ForeignKey(Stimulus, on_delete=models.CASCADE, related_name='trials')
    session = models.ForeignKey(Session, on_delete=models.CASCADE, related_name='trials')
    response = models.CharField(max_length=2)
    reward = models.BooleanField(null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    block = models.CharField(max_length=20)
    reward_probs_record = models.JSONField(default=dict)


class QuestionnaireQ(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE, related_name='questionnaire_q')
    questionnaire_name = models.CharField(max_length=100)
    subscale = models.CharField(max_length=40,blank=True,null=True)
    possible_answers = models.JSONField(default=dict)
    question = models.CharField(max_length=1000)
    answer = models.IntegerField()
    questionnaire_question_number = models.IntegerField()

alienartifacts/views.py
from .functions import *
import json
import urllib
from django.http import JsonResponse
from .models import Stimulus, Session, Subject, Trial, TutorialStimulus, RewardStimulus
from datetime import datetime
import numpy as np
import os, logging
from .global_variables import *

# Get an instance of a logger
logger = logging.getLogger('django')

# Views
def index(request):
    try:
        return consentform(request)
    except:
        logger.error('Something went wrong in the index function')


def consentform(request):
    try:
        link_url = 'alienartifacts:welcome'
        return render(request, "alienartifacts/consentform.html", {
            "link_url": link_url,
        })
    except:
        logger.error('Something went wrong in the consentform view function')


def welcome(request):
    logger.info('In welcome function')
    try:
        if request.method == "POST":
            form = RegistrationForm(request.POST)
            if form.is_valid():
                if not DEBUG:
                    ''' Begin reCAPTCHA validation '''
                    recaptcha_response = request.POST.get('g-recaptcha-response')
                    url = 'https://www.google.com/recaptcha/api/siteverify'
                    values = {
                        'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                        'response': recaptcha_response
                    }
                    data = urllib.parse.urlencode(values).encode()
                    req = urllib.request.Request(url, data=data)
                    response = urllib.request.urlopen(req)
                    result = json.loads(response.read().decode())
                    ''' End reCAPTCHA validation '''

                    if result['success']:
                        valid = True
                    else:
                        valid = False
                else:
                    valid = True
                if valid:
                    #Create variables to be entered
                    user_ID = form.cleaned_data["user_ID"]
                    subject_source = form.cleaned_data["subject_source"]
                    age = form.cleaned_data["age"]
                    gender = form.cleaned_data["gender"]
                    education = form.cleaned_data["education"]
                    start_time = form.cleaned_data["start_time"]
                    end_time = datetime.now() #Will update on each refresh
                    payment_token = getPaymentToken()
                    #Check if subject exists, if not create them
                    if Subject.objects.filter(external_ID=user_ID,external_source=subject_source).exists():
                        if DEPLOYMENT:
                            return alreadyCompleted(request)
                        subject = Subject.objects.filter(external_ID=user_ID)[0]
                    else:
                        subject = Subject(external_ID=user_ID, external_source=subject_source, age=age, gender=gender,
                                          education=education)
                        subject.save()
                    #Create a new Session
                    # subject.sessions.add(session)
                    if TASK == 'example-generalization':
                        conditioning, generalization = checkSessionAtts(task=TASK,STIMULI_BLOCK_0=STIMULI_BLOCK_0,
                                                                        STIMULI_BLOCK_1=STIMULI_BLOCK_1)
                        reward_rules, valid_keys, conversion = assignKeys(REWARD_RULES, POSSIBLE_KEYS,
                                                                          BLOCK_CATEGORIES)
                        session = Session(start_time=start_time, end_time=end_time, payment_token=payment_token,
                                          subject=subject, conditioning_attributes=conditioning,
                                          generalization_attributes=generalization, key_conversion=conversion)
                        session.task = TASK
                        session.save()
                        #Organize Stimulus Information
                        stimulus_order_block_0 = getStimulusOrder(STIMULUS_COMBINATIONS_BLOCK_0, N_TRIALS_BLOCK_0,
                                                      trials_per_stim=TRIALS_PER_STIM_BLOCK_0, structured=STRUCTURED)
                        stimulus_order_block_1 = getStimulusOrder(STIMULUS_COMBINATIONS_BLOCK_1, N_TRIALS_BLOCK_1,
                                                      trials_per_stim=TRIALS_PER_STIM_BLOCK_1, structured=STRUCTURED)
                        stimulus_order_block_1 = [indx+len(STIMULUS_COMBINATIONS_BLOCK_0) for indx in
                                                  stimulus_order_block_1]
                        request.session['stimulus_order'] = stimulus_order_block_0 + stimulus_order_block_1
                        request.session['block'] = (np.append(np.zeros(N_TRIALS_BLOCK_0),
                                                              np.ones(N_TRIALS_BLOCK_1))).astype(int).tolist()
                        request.session['reward_rules'] = reward_rules
                        request.session['valid_keys'] = valid_keys
                    elif (TASK == 'context-generalization') or (TASK == 'context-generalization_v1') or \
                            (TASK == 'context-generalization_v2') or (TASK == 'diagnostic'):
                        set_1, set_2 = checkSessionAtts(task=TASK,STIMULI_BLOCK_0=STIMULI_BLOCK_0,
                                                                        STIMULI_BLOCK_1=STIMULI_BLOCK_1)
                        reward_rules, valid_keys, conversion = assignKeys(REWARD_RULES, POSSIBLE_KEYS, BLOCK_CATEGORIES)
                        session = Session(start_time=start_time, end_time=end_time, payment_token=payment_token,
                                          subject=subject, set_1_attribute=set_1, set_2_attribute=set_2,
                                          key_conversion=conversion)
                        session.task = TASK
                        session.save()
                        stimulus_order_block_0 = getStimulusOrder(STIMULUS_COMBINATIONS_BLOCK_0, N_TRIALS_BLOCK_0,
                                                                  trials_per_stim=TRIALS_PER_STIM_BLOCK_0,
                                                                  structured=STRUCTURED)
                        stimulus_order_block_1 = getStimulusOrder(STIMULUS_COMBINATIONS_BLOCK_1, N_TRIALS_BLOCK_1,
                                                                  trials_per_stim=TRIALS_PER_STIM_BLOCK_1,
                                                                  structured=STRUCTURED)
                        stimulus_order_block_2 = getStimulusOrder(STIMULUS_COMBINATIONS_BLOCK_2, N_TRIALS_BLOCK_2,
                                                                  trials_per_stim=TRIALS_PER_STIM_BLOCK_2,
                                                                  structured=STRUCTURED)
                        request.session['stimulus_order'] = stimulus_order_block_0 + stimulus_order_block_1 + \
                                                            stimulus_order_block_2
                        request.session['block'] = (np.concatenate((np.zeros(N_TRIALS_BLOCK_0), \
                                                              np.ones(N_TRIALS_BLOCK_1), \
                                                              np.ones(N_TRIALS_BLOCK_2)*2))).astype(int).tolist()
                        request.session['reward_rules'] = reward_rules
                        request.session['valid_keys'] = valid_keys
                        if TASK == 'diagnostic':
                            request.session['diagnostic_block'] = 0
                    else:
                        raise ValueError(f'{TASK} is invalid for the TASK variable.')

                    logger.info(f'reward_rules = {reward_rules}')
                    logger.info(f'valid_keys = {valid_keys}')
                    logger.info(f'conversion = {conversion}')
                    #Set variables for this visit to the site
                    request.session['session_ID'] = session.id
                    request.session['subject_ID'] = subject.id
                    request.session['trial_number'] = 0
                    request.method = 'GET'
                    return instructions(request)
        if not DEBUG:
            recaptcha = {
                'bool': True,
                'src': 'https://www.google.com/recaptcha/api.js',
                'site_key': "6Lc7Jd8ZAAAAABnqL1VW3WOLjEcI2pb4kEAAZZLq"
            }
        else:
            recaptcha = {
                'bool': False,
                'src': '',
                'site_key': ""
            }
        form = RegistrationForm(initial={'start_time': datetime.now()})
        return render(request, "alienartifacts/welcome.html", {
            "form": form,
            "recaptcha": recaptcha
        })
    except:
        logger.error('Something went wrong in the welcome function')


def checkAttention(formset,form_att_check):
    # Check if they got the psych history one right
    if form_att_check.cleaned_data["attention_checkbox"] is not None:
        pass_attention_checkbox = ('pass_attention_check' in form_att_check.cleaned_data["attention_checkbox"]) and \
                                    ('fail_attention_check' not in form_att_check.cleaned_data["attention_checkbox"])
    else:
        pass_attention_checkbox = False
    # Check for the hidden questions
    correct_responses = 0
    for question in formset.cleaned_data:
        if question['questionnaire_name'] == 'att_check':
            correct_responses += question['answer']
    pass_hidden_questions = (correct_responses == 2)
    # Return if they got both right
    return pass_hidden_questions & pass_attention_checkbox


def attentionfailure(request):
    # They failed the attention test

alienartifacts/templates/alienartifacts/alreadycompleted.html
{% extends "alienartifacts/layout.html" %}

{% block body %}
    <body>
    <div label="exit_message">
        It looks like you've done this task before. Thanks for the interest, but we need fresh subjects!
    </div>
    </body>
{% endblock %}

alienartifacts/templates/alienartifacts/attentionfailure.html
{% extends "alienartifacts/layout.html" %}

{% block body %}
    <body>
    <div label="exit_message">
        Unfortunately, you failed the checks to see if you were reading the questions closely. Please use the code
        {{ token }}. You can close this window.
{#        Unfortunately, you failed the checks to see if you were reading the questions closely. You can close this window.#}
    </div>
    </body>
{% endblock %}

alienartifacts/templates/alienartifacts/consentform.html
{% extends "alienartifacts/layout.html" %}

{% block body %}

    <h1>Online Consent for Participation</h1>

    <p align="center">&nbsp;</p>
    <p align="center">YALE UNIVERSITY</p>
    <p align="center">&nbsp;YALE UNIVERSITY SCHOOL OF MEDICINE</p>
    <p align="center">DEPARTMENT OF PSYCHIATRY</p>
    <p align="center">&nbsp;</p>
    <p align="center">&nbsp;</p>
    <p align="center"><strong>Title</strong>: Latent State&nbsp;Reinforcement-Learning</p>
    <p align="center">&nbsp;</p>
    <p align="center"><strong>Principal Investigator:&nbsp;</strong>John Murray, Ph.D.,&nbsp;<a href="mailto:john.murray@yale.edu" style="font-size:inherit">john.murray@yale.edu</a></p>
    <p align="center"><strong>Contact:&nbsp;</strong>Warren Woodrich Pettine, M.D.,&nbsp;<a href="http://warren.pettine@yale.edu/" style="font-size:inherit">warren.pettine@yale.edu</a></p>
    <p>&nbsp;</p>
    <p><strong>Introduction</strong></p>
    <p>You are being asked to join a research study.&nbsp; The following information will explain the purpose of the study, what you will be asked to do, and the potential risks and benefits.</p>
    <p>&nbsp;</p>
    <p><strong>Purpose</strong></p>
    <p>The purpose of this study is to learn about cognitive strategies in the context of a rule-based reinforcement-learning task. You are being asked to participate because you are a Prolific or mTURK worker interested in this study. We are particularly interested in how psychiatric traits relate to cognitive strategies.</p>
    <p>&nbsp;</p>
    <p><strong>Procedures</strong></p>
    <p>If you choose to participate in the study, you will perform a rule-based reinforcement-learning task. You will be shown visual cues and you need to respond by pressing a key. Through trial and error, you will learn the correct key to press for a given stimulus. There is a tutorial and then several test blocks. You will also answer some questions about non-identifiable demographic information (e.g., gender, age, educational level), lifestyle (e.g., research familiarity), psychiatric history (e.g. formal diagnosis of autism), as well as questions from standard psychiatric questionnaires. You will earn $4&nbsp;for successfully completing the questionnaires and tutorial, as well as another $4&nbsp;for completing the task. You will earn up to $4&nbsp;bonus for responding accurately. This study should take less than 60 minutes to complete. We do not anticipate any risks during the study beyond those typically experienced on a day-to-day basis.&nbsp;</p>
    <p>&nbsp;</p>
    <p><strong>Possible Benefits</strong></p>
    <p>This research is not designed to benefit you directly. However, knowledge gained from the results may help us to better understand cognitive function, particularly those with psychiatric disorders.</p>
    <p>&nbsp;</p>
    <p><strong>Possible Risks</strong></p>
    <p>There is no physical or psychological risk in this study. There is a slight risk regarding the confidentiality of your participation in this study, if information about you becomes known to persons outside this study.&nbsp; The researchers are required to keep your study information confidential, however, so the risk of breach of confidentiality is very low.</p>
    <p>&nbsp;</p>
    <p><strong>Privacy / Confidentiality</strong></p>
    <p>We will not collect any identifying information such as your name. It is a possible that your work IDs is linked to your public profile. However, the worker IDs will only be collected for the purposes of distributing compensation. Furthermore, only the researchers involved in this study and those responsible for research oversight will have access to the worker IDs and other information you provide. The worker IDs will never be posted or published. Therefore, while your responses in the study are anonymous, your participation is confidential.&nbsp;</p>
    <p>&nbsp;</p>
    <p><strong>Voluntary Participation</strong></p>
    <p>Participation in this study is completely voluntary.&nbsp; You are free to decline to participate, and to end participation at any time for any reason. Refusing to participate will involve no penalty or loss of benefits to which you are otherwise entitled. By providing consent, you have not given up any of your legal rights.</p>
    <p>&nbsp;</p>
    <p><strong>Questions</strong></p>
    <p>You have read the above description of the research study, including the risks and benefits involved. At this point, if you have questions regarding the study that you would like to have answered before you begin, please email the Principal Investigator as described below.</p>
    <p>&nbsp;</p>
    <p>If you have any further questions about this study, you may contact the investigator, [Dr. Warren Woodrich Pettine,&nbsp;<a href="http://warren.pettine@yale.edu/" style="font-size:inherit">warren.pettine@yale.edu</a>]. If you would like to talk with someone other than the researchers to discuss problems, concerns, and questions you may have concerning this research, or to discuss your rights as a research subject, you may contact the Yale Human Investigation Committee at (203) 785-4688.</p>

    <a id="to-task" href="{% url link_url %}">Consent to join study</a>
{% endblock %}

alienartifacts/templates/alienartifacts/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'alienartifacts:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

alienartifacts/templates/alienartifacts/diagnostic.html
{% extends "alienartifacts/layout.html" %}


{% block body %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {{ valid_keys|json_script:"valid_keys" }}
    <script type="text/javascript">
        var valid_keys = JSON.parse(document.getElementById('valid_keys').textContent);
    </script>

    <script type="text/javascript">
    var updateurl = "{% url 'alienartifacts:onepagediagnosticupdate' %}";
    {#var goodbyeurl = "{% url 'alienartifacts:goodbye' %}";#}
    var goodbyeurl = "{% url 'alienartifacts:onepagediagnostic' %}";
    var diagnostic_counter = {{ diagnostic_counter }}
    var block_trial_number = 0;
    var stimuli = {{ stimuli }};
    var responses = new Array();
    var hues = {{ obscured | safe }};
    var start_times = new Array();
    var end_times = new Array();
    var total_possible = 0;
    var block_possible = 0;
    var total_earned = 0;
    var block_earned = 0;
    var listening = false;
    var last = false;

    </script>


    {% load static %}
    <script src="{% static 'js/diagnostic.js' %}"></script>

    <h2 id="instructions" style="display: none;">
    {{ response_text }}
    </h2>

    <div id="block_intro">
        This is block {{ block_number }} from the onePageDiagnostic function.
    </div>

    <div id="image_shown">
    {% for url in stimulus_urls %}
        <img id="stimulus_{{ forloop.counter0 }}" alt="stimulus_{{ forloop.counter0 }}" src="{{ url }}" style="display: none;" class="center">
    {% endfor %}
    </div>

    <div id="diagnostic">
        "The count is " {{ diagnostic_counter }}
    </div>

    <div id="feedback_correct" style="display: none;">
        Rewarded! The power is growing...
        <img id="rewarded_stim" src="{{ reward_stim_urls.0 }}" style="display: none;" class="center">
    </div>


    <div id="feedback_incorrect" style="display: none;">
        Nothing happens. Bummer
        <img id="nonrewarded_stim" src="{{ reward_stim_urls.1 }}" style="display: none;" class="center">
    </div>


    <div id="results_summary">

    </div>


{% endblock %}

alienartifacts/templates/alienartifacts/feedback.html
{% extends "alienartifacts/layout.html" %}

{% block body %}
    <script>

    {#document.addEventListener('DOMContentLoaded', function () {#}
    function newTrial() {
        window.location.href= '/task';
    }
    {# });#}

    document.addEventListener('DOMContentLoaded', function() {
        setTimeout(newTrial, 2000)
    });
    </script>

    <h1>{{ response }}</h1>
    <body>

    </body>

{% endblock %}

alienartifacts/templates/alienartifacts/fishy.html
{% extends "alienartifacts/layout.html" %}

{% block body %}
    <body>
    <div label="exit_message">
        Aliens detected that you're up to no good. They zap you from their spaceship. Bubye.
    </div>
    </body>
{% endblock %}

alienartifacts/templates/alienartifacts/goodbye.html
{% extends "alienartifacts/layout.html" %}

{% block body %}

    <div id="exit_message">
        {{ message }}
    </div>

    <form action="{% url 'alienartifacts:goodbye' %}" method="post" class="pure-form pure-form-aligned">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="Submit" value="Submit">
    </form>

{% endblock %}

alienartifacts/templates/alienartifacts/onepagecontextgentask.html
{% extends "alienartifacts/layout.html" %}


{% block body %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {{ valid_keys|json_script:"valid_keys" }}
    <script type="text/javascript">
        var valid_keys = JSON.parse(document.getElementById('valid_keys').textContent);
    </script>

    <script type="text/javascript">
    var updateurl = "{% url 'alienartifacts:onepagecontextgenupdate' %}";
    {#var goodbyeurl = "{% url 'alienartifacts:goodbye' %}";#}
    var goodbyeurl = "{% url 'alienartifacts:onepagecontextgentask' %}";
    var block_trial_number = 0;
    var stimuli = {{ stimuli }};
    var responses = new Array();
    var hues = {{ obscured | safe }};
    var start_times = new Array();
    var end_times = new Array();
    var total_possible = 0;
    var block_possible = 0;
    var total_earned = 0;
    var block_earned = 0;
    var listening = false;
    var last = false;

    </script>


    {% load static %}
    <script src="{% static 'js/onepagecontextgentask.js' %}"></script>

    <h2 id="instructions" style="display: none;">
    {{ response_text }}
    </h2>

    <div id="planet_intro">
    {{ planet_intro }}
    </div>

    <div id="image_shown">
    {% for url in stimulus_urls %}
        <img id="stimulus_{{ forloop.counter0 }}" alt="stimulus_{{ forloop.counter0 }}" src="{{ url }}" style="display: none;" class="center">
    {% endfor %}
    </div>


    <div id="feedback_correct" style="display: none;">
        Rewarded! The power is growing...
        <img id="rewarded_stim" src="{{ reward_stim_urls.0 }}" style="display: none;" class="center">
    </div>


    <div id="feedback_incorrect" style="display: none;">
        Nothing happens. Bummer
        <img id="nonrewarded_stim" src="{{ reward_stim_urls.1 }}" style="display: none;" class="center">
    </div>


    <div id="results_summary">

    </div>


{% endblock %}

alienartifacts/templates/alienartifacts/onepagetask.html
{% extends "alienartifacts/layout.html" %}


{% block body %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {{ valid_keys|json_script:"valid_keys" }}
    <script type="text/javascript">
        var valid_keys = JSON.parse(document.getElementById('valid_keys').textContent);
    </script>

    <script type="text/javascript">
    var updateurl = "{% url 'alienartifacts:onepageexamplegenupdate' %}";
    var goodbyeurl = "{% url 'alienartifacts:goodbye' %}";
    var block_trial_number = 0;
    var stimuli = {{ stimuli }};
    var responses = new Array();
    var hues = {{ obscured | safe }};
    var start_times = new Array();
    var end_times = new Array();
    var total_possible = 0;
    var block_possible = 0;
    var total_earned = 0;
    var block_earned = 0;
    var listening = false;
    var last = false;

    </script>


    {% load static %}
    <script src="{% static 'js/onepagetask.js' %}"></script>

    <h2 id="instructions" style="display: none;">
        Shake (press 'v'), slap (press 'b'), or kick (press 'n')
    </h2>

    <div id="image_shown">
    {% for url in stimulus_urls %}
        <img id="stimulus_{{ forloop.counter0 }}" alt="stimulus_{{ forloop.counter0 }}" src="{{ url }}" style="display: none;" class="center">
    {% endfor %}
    </div>


    <div id="feedback_correct" style="display: none;">
        Rewarded! The power is growing...
        <img id="rewarded_stim" src="{{ reward_stim_urls.0 }}" style="display: none;" class="center">
    </div>


    <div id="feedback_incorrect" style="display: none;">
        Nothing happens. Bummer
        <img id="nonrewarded_stim" src="{{ reward_stim_urls.1 }}" style="display: none;" class="center">
    </div>


    <div id="results_summary">

    </div>


{% endblock %}

alienartifacts/templates/alienartifacts/questionnaires.html
{% extends "alienartifacts/layout.html" %}

{% block body %}
    <h1>Questions! </h1>

    <div>
    Please answer the following questions. Make sure to read them carefully, as several are designed to see if you're
        paying attention. There are a lot of questions, and some may feel personal. Keep in mind that all answers are
        confidential. Furthermore, the intention of our research is to help people. The more honest you are in each
        question, the higher the quality of our findings. Let's do this together!
     <br>
    <br>
    <em> ***questions referring to casual interaction with acquaintances, rather than special
        relationships such as with close friends and family members.</em>
    </div>

    <form action="{% url 'alienartifacts:questionnaires' %}" method="post" class="pure-form pure-form-aligned form_style">
        {% csrf_token %}

        {{ form_substance.as_ul }}

        {{ formset.as_ul }}

        {{ form_att_check.as_ul }}

        {{ form_mh.as_ul }}

        <input type="submit" name="Submit">
    </form>


{% endblock %}

alienartifacts/templates/alienartifacts/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'alienartifacts:detail' question.id %}">Vote again?</a>

alienartifacts/templates/alienartifacts/token.html
{% extends "alienartifacts/layout.html" %}

{% block body %}

    
    <div id="token_message">
        Your payment code for the task is {{ payment_token }}. To register for payment, please enter that in the Prolific
    page. You can close this window.
    </div>


{% endblock %}